"""Generate FASM with the embedded DSL: macros, repetition, and scopes.

Run it:

    uv run python examples/01_generate.py

The eDSL leans on plain Python. A "macro" is a function, repetition is a ``for``
loop, and :meth:`FasmBuilder.scope` supplies the one ergonomic feature Python
lacks: nesting of dotted feature names.
"""

from fasm_toolkit import FasmBuilder, ValueFormat, bits


def configure_lut(b: FasmBuilder, init: int) -> None:
    """Write a 16-bit LUT init and enable its output mux (a reusable macro)."""
    b.set("LUT.INIT", init, width=16)
    with b.scope("MUX"):
        b.enable("OUT_SEL")


def build_design() -> str:
    """Build a 2x2 grid of configured tiles and return the emitted FASM."""
    b = FasmBuilder()
    b.comment(" generated by examples/01_generate.py")

    for x in range(2):
        for y in range(2):
            with b.scope(f"TILE_X{x}Y{y}"):
                # Each tile gets a different init so the output is interesting.
                configure_lut(b, 0xABCD ^ ((x << 8) | (y << 4)))
                # A small routing field, addressed with bits(high, low).
                b.set(
                    "ROUTING.JUMP",
                    x * 2 + y,
                    at=bits(3, 0),
                    fmt=ValueFormat.VERILOG_BINARY,
                )

    return b.build().to_string()


def main() -> str:
    """Build the demo design and return its emitted FASM text."""
    return build_design()


if __name__ == "__main__":
    print(main(), end="")
